apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  labels:
    app: counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: NAME
          value: "KHUN"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: counter-index-file
          mountPath: /usr/share/nginx/html/
      volumes:
        - name: counter-index-file
          configMap:
            name: counter-config