apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  labels:
    app: counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: NAME
          value: "KHUN"
        - name: MYSQL_DB_HOST
          value: mysql           
        - name: MYSQL_DB_PORT
          value: "3306"            
        - name: MYSQL_DB_NAME
          value: "khundev"            
        - name: MYSQL_DB_USER
          value: "admin"             
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        ports:
        - containerPort: 80
        volumeMounts:
        - name: counter-index-file
          mountPath: /usr/share/nginx/html/
      volumes:
        - name: counter-index-file
          configMap:
            name: counter-config