apiVersion: v1
kind: Service
metadata:
  name: counter-service
  namespace: default
  labels: 
    app: counter
spec:
  selector:
    app: counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer